# Generated by Django 4.2.7 on 2024-09-28 18:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_hearthstoneversion_api_hearths_version_2120a9_idx'), ('api', '0003_releasechannel'), ('api', '0004_alter_release_hearthstone_version_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('accessibility_version', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=api.models.get_release_file_name)),
                ('hearthstone_version', models.CharField(max_length=100)),
            ],
            options={
                'get_latest_by': 'accessibility_version',
            },
        ),
        migrations.CreateModel(
            name='ReleaseChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('releases', models.ManyToManyField(to='api.release')),
            ],
        ),
    ]
