# Generated by Django 4.2.7 on 2025-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_squashed_0004_alter_release_hearthstone_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='assembly_csharp_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
